stages:
  - build
  - name: deploy-dev
    if: branch = develop
  - name: deploy-prod
    if: branch = master

jobs:
  include:
    - stage: build
      workspaces:
        create:
          name: build
          paths:
            - .
      before_script:
        - curl
            --silent
            --location
            --output awscliv2.zip
            https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        - unzip -q awscliv2.zip
        - ./aws/install --install-dir $(pwd)/tmp/aws --bin-dir $(pwd)/tmp/bin
        - export
            AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
        - ./tmp/bin/aws ecr get-login-password --region eu-west-1
          |
          docker login
            --username AWS
            --password-stdin
            295345423838.dkr.ecr.eu-west-1.amazonaws.com
        - export
            AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
        - ./tmp/bin/aws ecr get-login-password --region eu-west-1
          |
          docker login
            --username AWS
            --password-stdin
            179679461214.dkr.ecr.eu-west-1.amazonaws.com
      script:
        - set -o errexit
        - docker build --tag web-client .
        - tag=$(git rev-parse HEAD)
        - docker tag web-client 295345423838.dkr.ecr.eu-west-1.amazonaws.com/flexxi/web-client:$tag
        - docker tag web-client 179679461214.dkr.ecr.eu-west-1.amazonaws.com/flexxi/web-client:$tag
        - docker push 295345423838.dkr.ecr.eu-west-1.amazonaws.com/flexxi/web-client:$tag
        - docker push 179679461214.dkr.ecr.eu-west-1.amazonaws.com/flexxi/web-client:$tag

    - stage: deploy-dev
      workspaces:
        use: build
      git:
        clone: false
      before_script:
        - cd ${TRAVIS_REPO_SLUG}
        - curl
            --silent
            --location
            --output ./tmp/bin/kubectl
            https://storage.googleapis.com/kubernetes-release/release/$(
              curl
                --silent
                https://storage.googleapis.com/kubernetes-release/release/stable.txt
            )/bin/linux/amd64/kubectl
        - chmod +x ./tmp/bin/kubectl
        - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          |
          HELM_INSTALL_DIR=./tmp/bin/ PATH=$(pwd)/tmp/bin:${PATH} bash
        - export
            AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
        - ./tmp/bin/aws s3 cp s3://swiftech-config-dev/config ./tmp/.kube/config
      script:
        - PATH=./tmp/bin:${PATH} ./tmp/bin/helm
            --kubeconfig ./tmp/.kube/config
            --namespace flexxi
            upgrade
            flexxi-web-client
            helm/flexxi-web-client
            --install
            --set image.tag=$(git rev-parse HEAD)
            --values helm/flexxi-web-client/values.dev.yaml

    - stage: deploy-prod
      workspaces:
        use: build
      git:
        clone: false
      before_script:
        - cd ${TRAVIS_REPO_SLUG}
        - curl
            --silent
            --location
            --output ./tmp/bin/kubectl
            https://storage.googleapis.com/kubernetes-release/release/$(
              curl
                --silent
                https://storage.googleapis.com/kubernetes-release/release/stable.txt
            )/bin/linux/amd64/kubectl
        - chmod +x ./tmp/bin/kubectl
        - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          |
          HELM_INSTALL_DIR=./tmp/bin/ PATH=$(pwd)/tmp/bin:${PATH} bash
        - export
            AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
        - ./tmp/bin/aws s3 cp s3://swiftech-config/config ./tmp/.kube/config
      script:
        - PATH=./tmp/bin:${PATH} ./tmp/bin/helm
            --kubeconfig ./tmp/.kube/config
            --namespace flexxi
            upgrade
            flexxi-web-client
            helm/flexxi-web-client
            --install
            --set image.tag=$(git rev-parse HEAD)
            --values helm/flexxi-web-client/values.prod.yaml
