image:
  repository: 179679461214.dkr.ecr.eu-west-1.amazonaws.com/flexxi/web-client

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: web.flexxi.care
      paths:
        - path: /
  tls:
   - secretName: flexxi-web-client-tls
     hosts:
       - web.flexxi.care
